# words.py

terms = {
    "Электричество": "l'électricité",
    "Электрический ток": "le courant électrique",
    "Напряжение": "la tension",
    "Сила тока": "l'intensité du courant",
    "Сопротивление": "la résistance",
    "Мощность": "la puissance",
    "Частота": "la fréquence",
    "Фаза": "la phase",
    "Ноль": "le neutre",
    "Заземление": "la mise à la terre",
    "Смещение фаз": "le déphasage",
    "Трёхфазный": "le triphasé",
    "Однофазный": "le monophasé",
    "Переменный ток": "le courant alternatif",
    "Постоянный ток": "le courant continu",
    "Коэффициент мощности": "le facteur de puissance",
    "Перенапряжение": "la surtension",
    "Пониженное напряжение": "la sous-tension",
    "Потери напряжения": "la perte de charge",
    "Гармоники": "les harmoniques",
    "Электрический кабель": "le câble électrique",
    "Электрический провод": "le fil électrique",
    "Гибкий кабель": "le câble souple",
    "Жёсткий кабель": "le câble rigide",
    "Медный кабель": "le câble en cuivre",
    "Алюминиевый кабель": "le câble en aluminium",
    "Сечение кабеля": "la section de câble",
    "Кабель с двойной изоляцией": "le câble à double isolation",
    "Плоский кабель": "le câble plat",
    "Круглый кабель": "le câble rond",
    "Экранированный кабель": "le câble blindé",
    "Витая пара": "le câble torsadé",
    "Многожильный кабель": "le câble multiconducteur",
    "Одножильный кабель": "le câble monoconducteur",
    "Защитная гофра": "la gaine de protection",
    "Кабельный лоток": "le chemin de câble",
    "Распределительная коробка": "la boîte de dérivation",
    "Встраиваемая коробка": "la boîte d'encastrement",
    "Кабельный наконечник": "l'embout de câble",
    "Быстрый соединитель": "le connecteur rapide",
    "Электрический щит": "le tableau électrique",
    "Автоматический выключатель": "le disjoncteur",
    "Дифференциальный автомат": "le disjoncteur différentiel",
    "Предохранитель": "le fusible",
    "Реле": "le relais",
    "Контактор": "le contacteur",
    "Трансформатор": "le transformateur",
    "Электросчётчик": "le compteur électrique",
    "ОПН": "le parafoudre",
    "Клеммная колодка": "le bornier de raccordement",
    "Монтажная панель": "la platine de montage",
    "Дифференциальный выключатель": "l'interrupteur différentiel",
    "Разъединитель": "le sectionneur",
    "Варистор": "la varistance",
    "Конденсатор": "le condensateur",
    "Освещение": "l'éclairage",
    "Лампочка": "l'ampoule",
    "Встраиваемый светильник": "le spot encastrable",
    "Потолочный светильник": "le plafonnier",
    "Настенный светильник": "l'applique murale",
    "Обычный выключатель": "l'interrupteur simple",
    "Перекрёстный выключатель": "l'interrupteur va-et-vient",
    "Диммер": "le variateur de lumière",
    "Датчик движения": "le détecteur de mouvement",
    "Светодиодный прожектор": "le projecteur LED",
    "Кабельный лоток": "le chemin de câbles",
    "Кабельный короб": "la goulotte électrique",
    "Кабельная стяжка": "le collier de serrage",
    "Кабельный хомут": "l'attache de câble",
    "Обжимные клещи": "la pince à sertir",
    "Изолированная отвертка": "le tournevis isolé",
    "Инструмент для снятия изоляции": "le dégaine-câble",
    "Дрель": "la perceuse",
    "Коронка": "la scie-cloche",
    "Изолирующие перчатки": "les gants isolants",
    "Изолирующий коврик": "le tapis isolant",
    "Изолированная стремянка": "l'escabeau isolé",
    "Мультиметр": "le multimètre",
    "Токоизмерительные клещи": "la pince ampèremétrique",
    "Тестер напряжения": "le testeur de tension",
    "Мегаомметр": "le mégohmmètre",
    "Детектор кабелей": "le détecteur de câbles",
    "Анализатор сети": "l'analyseur de réseau",
    "Проверка изоляции": "le contrôle d'isolement",
    "Измерение сопротивления": "la mesure de résistance",
    "Проверка целостности": "la mesure de continuité",
    "Проверка заземления": "le test de terre",
    "Электрические нормы": "les normes électriques",
    "Класс изоляции": "la classe d'isolation",
    "Защита от перенапряжений": "la protection contre les surtensions",
    "Защита от коротких замыканий": "la protection contre les courts-circuits",
    "Дифференциальная защита": "la protection différentielle",
    "Зона безопасности": "la zone de sécurité",
    "Охранная зона": "le périmètre de protection",
    "Средства индивидуальной защиты": "l'équipement de protection individuelle",
    "Предупреждающий знак": "la balise de sécurité",
    "Система аварийного отключения": "le système de coupure d'urgence"
}
